---
title: "Maximum Diva"
author: "Christopher Boyer"
date: "8/20/2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}


source("0_packages_and_helpers/0_load_packages.R")
source("0_packages_and_helpers/1_load_helpers.R")
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
options(kableExtra.auto_format = FALSE)

table1 <- read_rds("__data/results/table1.rds")
table2 <- read_rds("__data/results/table2.rds")
table3 <- read_rds("__data/results/table3.rds")

```


```{r, echo=FALSE, results='asis'}

knitr::kable(
  table1,
  digits = 3,
  format = "html",
  col.names = c(
    "Variable",
    "Treatment",
    "Control",
    "$p$-value",
    "Treatment",
    "Control",
    "$p$-value"
  ),
  align = c("l", "c", "c", "c", "c", "c", "c"),
  caption = "Baseline balance",
  booktabs = TRUE,
  escape = FALSE
) %>%
  kable_styling(font_size = 9, bootstrap_options = "striped") %>%
  group_rows("Socio-demographic controls", 1, 15, italic = TRUE, bold = FALSE) %>%
  group_rows("Primary outcomes", 16, 22, italic = TRUE, bold = FALSE) %>%
  group_rows("Secondary outcomes", 23, 27, italic = TRUE, bold = FALSE) %>% 
  group_rows("", 28, 32, indent = FALSE, hline_before = TRUE) %>%
  add_header_above(c(" ", "($N = 2364$; $M = 40$)" = 3, "($N = 2430$; $M = 40$)" = 3), escape = FALSE) %>%
  add_header_above(c(" ", "Baseline" = 3, "Endline" = 3), escape = FALSE, line = FALSE) 


```


```{r, echo=FALSE, results='asis'}

knitr::kable(
  table2,
  digits = 3,
  format = "html",
  col.names = c(
    "",
    "$\\widehat{\\tau}$",
    "95\\% CI",
    "$p$-value",
    "$\\widehat{\\tau}$",
    "95\\% CI",
    "$p$-value"
  ),
  align = c("l", "c", "c", "c", "c", "c", "c"),
  caption = "Intention-to-treat effects",
  booktabs = TRUE,
  escape = FALSE
) %>%
  kable_styling(font_size = 9, bootstrap_options = "striped") %>%
  group_rows("Primary outcomes", 1, 7, italic = TRUE, bold = FALSE) %>%
  group_rows("Secondary outcomes", 8, 12, italic = TRUE, bold = FALSE) %>%
  add_header_above(c(" ", "Unadjusted" = 3, "Adjusted" = 3))


```


```{r, echo=FALSE, results='asis'}

knitr::kable(
  table3,
  digits = 3,
  format = "html",
  col.names = c(
    "",
    "$\\widehat{\\tau}$",
    "95\\% CI",
    "$\\widehat{\\tau}$",
    "95\\% CI"
  ),
  align = c("l", "c", "c", "c", "c"),
  caption = "Compliance effects",
  booktabs = TRUE,
  escape = FALSE
) %>%
  kable_styling(font_size = 9, bootstrap_options = "striped") %>%
  group_rows("Primary outcomes", 1, 7, italic = TRUE, bold = FALSE) %>%
  group_rows("Secondary outcomes", 8, 12, italic = TRUE, bold = FALSE) %>%
  add_header_above(c(" ", "IV" = 2, "IPW" = 2))

```